### PR TITLE
do_optimize and Text Cleanup

### PR DESCRIPTION
**Pull request by Redblueflame**
## Original PR from LordBobRoss:
Changed the function do_easy_config_worldtickcpumax to do_optimize

Added Save Frequency enforcement changing 60 to 300 in Storage.eco during the creation process. Still needs to be added to the Advanced Config somewhere.

Went through and modified a few messages to be worded better.

### CODE REVIEW

**Comment by Redblueflame** [comment]
@LordBobRoss You removed the gui for choosing themself the worldtick ?

**Comment by LordBobRoss** [comment]
It doesn't have a GUI yet, just enforced a basic setting for the easy mode config and have yet to implement it in any fashion for Advanced users.

**Comment by Redblueflame** [comment]
The advanced user edit by themself the files so no need, but just a gui like Low cpu utilisation, Mediom, and high

**Comment by LordBobRoss** [comment]
I mostly just haven't gotten that far, will work on it in the coming days just wanted to get what Kicker was talking with me about last night with enforcing save times that are not capable of causing corruption. Just changed the default from 60 to 300 for new servers.

**Comment by Redblueflame** [comment]
Okey
I merge it on beta

**Pull request merged**
